INSTRUMENTS = [
    # ── FOREX (24 pairs) ──
    {"name": "EUR/USD", "yahoo": "EURUSD=X", "ig_epic": "CS.D.EURUSD.TODAY.IP", "market_type": "forex"},
    {"name": "GBP/USD", "yahoo": "GBPUSD=X", "ig_epic": "CS.D.GBPUSD.TODAY.IP", "market_type": "forex"},
    {"name": "USD/JPY", "yahoo": "USDJPY=X", "ig_epic": "CS.D.USDJPY.TODAY.IP", "market_type": "forex"},
    {"name": "USD/CHF", "yahoo": "USDCHF=X", "ig_epic": "CS.D.USDCHF.TODAY.IP", "market_type": "forex"},
    {"name": "AUD/USD", "yahoo": "AUDUSD=X", "ig_epic": "CS.D.AUDUSD.TODAY.IP", "market_type": "forex"},
    {"name": "USD/CAD", "yahoo": "USDCAD=X", "ig_epic": "CS.D.USDCAD.TODAY.IP", "market_type": "forex"},
    {"name": "NZD/USD", "yahoo": "NZDUSD=X", "ig_epic": "CS.D.NZDUSD.TODAY.IP", "market_type": "forex"},
    {"name": "EUR/GBP", "yahoo": "EURGBP=X", "ig_epic": "CS.D.EURGBP.TODAY.IP", "market_type": "forex"},
    {"name": "EUR/JPY", "yahoo": "EURJPY=X", "ig_epic": "CS.D.EURJPY.TODAY.IP", "market_type": "forex"},
    {"name": "GBP/JPY", "yahoo": "GBPJPY=X", "ig_epic": "CS.D.GBPJPY.TODAY.IP", "market_type": "forex"},
    {"name": "AUD/JPY", "yahoo": "AUDJPY=X", "ig_epic": "CS.D.AUDJPY.TODAY.IP", "market_type": "forex"},
    {"name": "EUR/AUD", "yahoo": "EURAUD=X", "ig_epic": "CS.D.EURAUD.TODAY.IP", "market_type": "forex"},
    {"name": "EUR/CAD", "yahoo": "EURCAD=X", "ig_epic": "CS.D.EURCAD.TODAY.IP", "market_type": "forex"},
    {"name": "GBP/AUD", "yahoo": "GBPAUD=X", "ig_epic": "CS.D.GBPAUD.TODAY.IP", "market_type": "forex"},
    {"name": "GBP/CAD", "yahoo": "GBPCAD=X", "ig_epic": "CS.D.GBPCAD.TODAY.IP", "market_type": "forex"},
    {"name": "GBP/CHF", "yahoo": "GBPCHF=X", "ig_epic": "CS.D.GBPCHF.TODAY.IP", "market_type": "forex"},
    {"name": "AUD/CAD", "yahoo": "AUDCAD=X", "ig_epic": "CS.D.AUDCAD.TODAY.IP", "market_type": "forex"},
    {"name": "AUD/NZD", "yahoo": "AUDNZD=X", "ig_epic": "CS.D.AUDNZD.TODAY.IP", "market_type": "forex"},
    {"name": "CAD/JPY", "yahoo": "CADJPY=X", "ig_epic": "CS.D.CADJPY.TODAY.IP", "market_type": "forex"},
    {"name": "CHF/JPY", "yahoo": "CHFJPY=X", "ig_epic": "CS.D.CHFJPY.TODAY.IP", "market_type": "forex"},
    {"name": "EUR/NZD", "yahoo": "EURNZD=X", "ig_epic": "CS.D.EURNZD.TODAY.IP", "market_type": "forex"},
    {"name": "NZD/CAD", "yahoo": "NZDCAD=X", "ig_epic": "CS.D.NZDCAD.TODAY.IP", "market_type": "forex"},
    {"name": "NZD/JPY", "yahoo": "NZDJPY=X", "ig_epic": "CS.D.NZDJPY.TODAY.IP", "market_type": "forex"},
    {"name": "NZD/CHF", "yahoo": "NZDCHF=X", "ig_epic": "CS.D.NZDCHF.TODAY.IP", "market_type": "forex"},

    # ── INDICES (14) ──
    {"name": "US 500", "yahoo": "^GSPC", "ig_epic": "IX.D.SPTRD.DAILY.IP", "market_type": "index"},
    {"name": "US Tech 100", "yahoo": "^IXIC", "ig_epic": "IX.D.NASDAQ.DAILY.IP", "market_type": "index"},
    {"name": "Wall Street", "yahoo": "^DJI", "ig_epic": "IX.D.DOW.DAILY.IP", "market_type": "index"},
    {"name": "Germany 40", "yahoo": "^GDAXI", "ig_epic": "IX.D.DAX.DAILY.IP", "market_type": "index"},
    {"name": "UK 100", "yahoo": "^FTSE", "ig_epic": "IX.D.FTSE.DAILY.IP", "market_type": "index"},
    {"name": "France 40", "yahoo": "^FCHI", "ig_epic": "IX.D.CAC.DAILY.IP", "market_type": "index"},
    {"name": "Japan 225", "yahoo": "^N225", "ig_epic": "IX.D.NIKKEI.DAILY.IP", "market_type": "index"},
    {"name": "Hong Kong 50", "yahoo": "^HSI", "ig_epic": "IX.D.HSI.DAILY.IP", "market_type": "index"},
    {"name": "Australia 200", "yahoo": "^AXJO", "ig_epic": "IX.D.ASX.DAILY.IP", "market_type": "index"},
    {"name": "EU Stocks 50", "yahoo": "^STOXX50E", "ig_epic": "IX.D.EURO50.DAILY.IP", "market_type": "index"},
    {"name": "Spain 35", "yahoo": "^IBEX", "ig_epic": "IX.D.IBEX.DAILY.IP", "market_type": "index"},
    {"name": "Italy 40", "yahoo": "FTSEMIB.MI", "ig_epic": "IX.D.MIB.DAILY.IP", "market_type": "index"},
    {"name": "China A50", "yahoo": "000001.SS", "ig_epic": "IX.D.CHINA.DAILY.IP", "market_type": "index"},
    {"name": "Volatility Index", "yahoo": "^VIX", "ig_epic": "IN.D.VIX.DAILY.IP", "market_type": "index"},

    # ── COMMODITIES (14) ──
    {"name": "Gold", "yahoo": "GC=F", "ig_epic": "CS.D.CFDGOLD.DAILY.IP", "market_type": "commodity"},
    {"name": "Silver", "yahoo": "SI=F", "ig_epic": "CS.D.CFDSILVER.DAILY.IP", "market_type": "commodity"},
    {"name": "Crude Oil WTI", "yahoo": "CL=F", "ig_epic": "CC.D.CFDUSO.DAILY.IP", "market_type": "commodity"},
    {"name": "Brent Crude", "yahoo": "BZ=F", "ig_epic": "CC.D.CFDBRN.DAILY.IP", "market_type": "commodity"},
    {"name": "Natural Gas", "yahoo": "NG=F", "ig_epic": "CC.D.CFDNGS.DAILY.IP", "market_type": "commodity"},
    {"name": "Copper", "yahoo": "HG=F", "ig_epic": "CC.D.CFDCOP.DAILY.IP", "market_type": "commodity"},
    {"name": "Platinum", "yahoo": "PL=F", "ig_epic": "CS.D.CFDPLAT.DAILY.IP", "market_type": "commodity"},
    {"name": "Palladium", "yahoo": "PA=F", "ig_epic": "CS.D.CFDPALLA.DAILY.IP", "market_type": "commodity"},
    {"name": "US Wheat", "yahoo": "ZW=F", "ig_epic": "CC.D.CFDWHE.DAILY.IP", "market_type": "commodity"},
    {"name": "US Corn", "yahoo": "ZC=F", "ig_epic": "CC.D.CFDCOR.DAILY.IP", "market_type": "commodity"},
    {"name": "US Soybeans", "yahoo": "ZS=F", "ig_epic": "CC.D.CFDSOY.DAILY.IP", "market_type": "commodity"},
    {"name": "Coffee", "yahoo": "KC=F", "ig_epic": "CC.D.CFDCOF.DAILY.IP", "market_type": "commodity"},
    {"name": "Sugar", "yahoo": "SB=F", "ig_epic": "CC.D.CFDSUG.DAILY.IP", "market_type": "commodity"},
    {"name": "Cotton", "yahoo": "CT=F", "ig_epic": "CC.D.CFDCOT.DAILY.IP", "market_type": "commodity"},

    # ── CRYPTO (99 Binance USDT pairs) ──
    {"name": "Bitcoin", "yahoo": "BTC-USD", "ig_epic": "CS.D.BITCOIN.TODAY.IP", "market_type": "crypto", "binance": "BTCUSDT"},
    {"name": "Ethereum", "yahoo": "ETH-USD", "ig_epic": "CS.D.ETHUSD.TODAY.IP", "market_type": "crypto", "binance": "ETHUSDT"},
    {"name": "BNB", "yahoo": "BNB-USD", "ig_epic": "CS.D.BNBUSD.TODAY.IP", "market_type": "crypto", "binance": "BNBUSDT"},
    {"name": "XRP", "yahoo": "XRP-USD", "ig_epic": "CS.D.XRPUSD.TODAY.IP", "market_type": "crypto", "binance": "XRPUSDT"},
    {"name": "Cardano", "yahoo": "ADA-USD", "ig_epic": "CS.D.ADAUSD.TODAY.IP", "market_type": "crypto", "binance": "ADAUSDT"},
    {"name": "Solana", "yahoo": "SOL-USD", "ig_epic": "CS.D.SOLUSD.TODAY.IP", "market_type": "crypto", "binance": "SOLUSDT"},
    {"name": "Dogecoin", "yahoo": "DOGE-USD", "ig_epic": "CS.D.DOGEUSD.TODAY.IP", "market_type": "crypto", "binance": "DOGEUSDT"},
    {"name": "Polkadot", "yahoo": "DOT-USD", "ig_epic": "CS.D.DOTUSD.TODAY.IP", "market_type": "crypto", "binance": "DOTUSDT"},
    {"name": "Polygon", "yahoo": "MATIC-USD", "ig_epic": "CS.D.MATICUSD.TODAY.IP", "market_type": "crypto", "binance": "MATICUSDT"},
    {"name": "Litecoin", "yahoo": "LTC-USD", "ig_epic": "CS.D.LTCUSD.TODAY.IP", "market_type": "crypto", "binance": "LTCUSDT"},
    {"name": "Avalanche", "yahoo": "AVAX-USD", "ig_epic": "CS.D.AVAXUSD.TODAY.IP", "market_type": "crypto", "binance": "AVAXUSDT"},
    {"name": "Chainlink", "yahoo": "LINK-USD", "ig_epic": "CS.D.LINKUSD.TODAY.IP", "market_type": "crypto", "binance": "LINKUSDT"},
    {"name": "Uniswap", "yahoo": "UNI-USD", "ig_epic": "CS.D.UNIUSD.TODAY.IP", "market_type": "crypto", "binance": "UNIUSDT"},
    {"name": "Stellar", "yahoo": "XLM-USD", "ig_epic": "CS.D.XLMUSD.TODAY.IP", "market_type": "crypto", "binance": "XLMUSDT"},
    {"name": "Cosmos", "yahoo": "ATOM-USD", "ig_epic": "CS.D.ATOMUSD.TODAY.IP", "market_type": "crypto", "binance": "ATOMUSDT"},
    {"name": "TRON", "yahoo": "TRX-USD", "ig_epic": "CS.D.TRXUSD.TODAY.IP", "market_type": "crypto", "binance": "TRXUSDT"},
    {"name": "Near", "yahoo": "NEAR-USD", "ig_epic": "", "market_type": "crypto", "binance": "NEARUSDT"},
    {"name": "Arbitrum", "yahoo": "ARB-USD", "ig_epic": "", "market_type": "crypto", "binance": "ARBUSDT"},
    {"name": "Optimism", "yahoo": "OP-USD", "ig_epic": "", "market_type": "crypto", "binance": "OPUSDT"},
    {"name": "Aptos", "yahoo": "APT-USD", "ig_epic": "", "market_type": "crypto", "binance": "APTUSDT"},
    {"name": "Injective", "yahoo": "INJ-USD", "ig_epic": "", "market_type": "crypto", "binance": "INJUSDT"},
    {"name": "Immutable", "yahoo": "IMX-USD", "ig_epic": "", "market_type": "crypto", "binance": "IMXUSDT"},
    {"name": "Render", "yahoo": "RNDR-USD", "ig_epic": "", "market_type": "crypto", "binance": "RNDRUSDT"},
    {"name": "Filecoin", "yahoo": "FIL-USD", "ig_epic": "CS.D.FILUSD.TODAY.IP", "market_type": "crypto", "binance": "FILUSDT"},
    {"name": "Hedera", "yahoo": "HBAR-USD", "ig_epic": "", "market_type": "crypto", "binance": "HBARUSDT"},
    {"name": "VeChain", "yahoo": "VET-USD", "ig_epic": "", "market_type": "crypto", "binance": "VETUSDT"},
    {"name": "Algorand", "yahoo": "ALGO-USD", "ig_epic": "", "market_type": "crypto", "binance": "ALGOUSDT"},
    {"name": "Fantom", "yahoo": "FTM-USD", "ig_epic": "", "market_type": "crypto", "binance": "FTMUSDT"},
    {"name": "Aave", "yahoo": "AAVE-USD", "ig_epic": "", "market_type": "crypto", "binance": "AAVEUSDT"},
    {"name": "Maker", "yahoo": "MKR-USD", "ig_epic": "", "market_type": "crypto", "binance": "MKRUSDT"},
    {"name": "The Graph", "yahoo": "GRT-USD", "ig_epic": "", "market_type": "crypto", "binance": "GRTUSDT"},
    {"name": "Sandbox", "yahoo": "SAND-USD", "ig_epic": "", "market_type": "crypto", "binance": "SANDUSDT"},
    {"name": "Decentraland", "yahoo": "MANA-USD", "ig_epic": "", "market_type": "crypto", "binance": "MANAUSDT"},
    {"name": "Axie Infinity", "yahoo": "AXS-USD", "ig_epic": "", "market_type": "crypto", "binance": "AXSUSDT"},
    {"name": "Theta", "yahoo": "THETA-USD", "ig_epic": "", "market_type": "crypto", "binance": "THETAUSDT"},
    {"name": "EOS", "yahoo": "EOS-USD", "ig_epic": "", "market_type": "crypto", "binance": "EOSUSDT"},
    {"name": "Tezos", "yahoo": "XTZ-USD", "ig_epic": "", "market_type": "crypto", "binance": "XTZUSDT"},
    {"name": "IOTA", "yahoo": "IOTA-USD", "ig_epic": "", "market_type": "crypto", "binance": "IOTAUSDT"},
    {"name": "NEO", "yahoo": "NEO-USD", "ig_epic": "", "market_type": "crypto", "binance": "NEOUSDT"},
    {"name": "Flow", "yahoo": "FLOW-USD", "ig_epic": "", "market_type": "crypto", "binance": "FLOWUSDT"},
    {"name": "ApeCoin", "yahoo": "APE-USD", "ig_epic": "", "market_type": "crypto", "binance": "APEUSDT"},
    {"name": "Cronos", "yahoo": "CRO-USD", "ig_epic": "", "market_type": "crypto", "binance": "CROUSDT"},
    {"name": "Quant", "yahoo": "QNT-USD", "ig_epic": "", "market_type": "crypto", "binance": "QNTUSDT"},
    {"name": "Chiliz", "yahoo": "CHZ-USD", "ig_epic": "", "market_type": "crypto", "binance": "CHZUSDT"},
    {"name": "Enjin", "yahoo": "ENJ-USD", "ig_epic": "", "market_type": "crypto", "binance": "ENJUSDT"},
    {"name": "1inch", "yahoo": "1INCH-USD", "ig_epic": "", "market_type": "crypto", "binance": "1INCHUSDT"},
    {"name": "Zcash", "yahoo": "ZEC-USD", "ig_epic": "", "market_type": "crypto", "binance": "ZECUSDT"},
    {"name": "Dash", "yahoo": "DASH-USD", "ig_epic": "", "market_type": "crypto", "binance": "DASHUSDT"},
    {"name": "Compound", "yahoo": "COMP-USD", "ig_epic": "", "market_type": "crypto", "binance": "COMPUSDT"},
    {"name": "SushiSwap", "yahoo": "SUSHI-USD", "ig_epic": "", "market_type": "crypto", "binance": "SUSHIUSDT"},
    {"name": "Curve", "yahoo": "CRV-USD", "ig_epic": "", "market_type": "crypto", "binance": "CRVUSDT"},
    {"name": "Synthetix", "yahoo": "SNX-USD", "ig_epic": "", "market_type": "crypto", "binance": "SNXUSDT"},
    {"name": "Yearn", "yahoo": "YFI-USD", "ig_epic": "", "market_type": "crypto", "binance": "YFIUSDT"},
    {"name": "Basic Attention", "yahoo": "BAT-USD", "ig_epic": "", "market_type": "crypto", "binance": "BATUSDT"},
    {"name": "Kava", "yahoo": "KAVA-USD", "ig_epic": "", "market_type": "crypto", "binance": "KAVAUSDT"},
    {"name": "Waves", "yahoo": "WAVES-USD", "ig_epic": "", "market_type": "crypto", "binance": "WAVESUSDT"},
    {"name": "Zilliqa", "yahoo": "ZIL-USD", "ig_epic": "", "market_type": "crypto", "binance": "ZILUSDT"},
    {"name": "OMG Network", "yahoo": "OMG-USD", "ig_epic": "", "market_type": "crypto", "binance": "OMGUSDT"},
    {"name": "Bancor", "yahoo": "BNT-USD", "ig_epic": "", "market_type": "crypto", "binance": "BNTUSDT"},
    {"name": "Gala", "yahoo": "GALA-USD", "ig_epic": "", "market_type": "crypto", "binance": "GALAUSDT"},
    {"name": "Loopring", "yahoo": "LRC-USD", "ig_epic": "", "market_type": "crypto", "binance": "LRCUSDT"},
    {"name": "Celo", "yahoo": "CELO-USD", "ig_epic": "", "market_type": "crypto", "binance": "CELOUSDT"},
    {"name": "Osmosis", "yahoo": "OSMO-USD", "ig_epic": "", "market_type": "crypto", "binance": "OSMOUSDT"},
    {"name": "dYdX", "yahoo": "DYDX-USD", "ig_epic": "", "market_type": "crypto", "binance": "DYDXUSDT"},
    {"name": "Lido DAO", "yahoo": "LDO-USD", "ig_epic": "", "market_type": "crypto", "binance": "LDOUSDT"},
    {"name": "Stargate", "yahoo": "STG-USD", "ig_epic": "", "market_type": "crypto", "binance": "STGUSDT"},
    {"name": "Blur", "yahoo": "BLUR-USD", "ig_epic": "", "market_type": "crypto", "binance": "BLURUSDT"},
    {"name": "Pepe", "yahoo": "PEPE24478-USD", "ig_epic": "", "market_type": "crypto", "binance": "PEPEUSDT"},
    {"name": "Floki", "yahoo": "FLOKI-USD", "ig_epic": "", "market_type": "crypto", "binance": "FLOKIUSDT"},
    {"name": "Bonk", "yahoo": "BONK-USD", "ig_epic": "", "market_type": "crypto", "binance": "BONKUSDT"},
    {"name": "Sei", "yahoo": "SEI-USD", "ig_epic": "", "market_type": "crypto", "binance": "SEIUSDT"},
    {"name": "Sui", "yahoo": "SUI-USD", "ig_epic": "", "market_type": "crypto", "binance": "SUIUSDT"},
    {"name": "Celestia", "yahoo": "TIA-USD", "ig_epic": "", "market_type": "crypto", "binance": "TIAUSDT"},
    {"name": "Jupiter", "yahoo": "JUP-USD", "ig_epic": "", "market_type": "crypto", "binance": "JUPUSDT"},
    {"name": "Wormhole", "yahoo": "W-USD", "ig_epic": "", "market_type": "crypto", "binance": "WUSDT"},
    {"name": "Ethena", "yahoo": "ENA-USD", "ig_epic": "", "market_type": "crypto", "binance": "ENAUSDT"},
    {"name": "Pendle", "yahoo": "PENDLE-USD", "ig_epic": "", "market_type": "crypto", "binance": "PENDLEUSDT"},
    {"name": "Pyth Network", "yahoo": "PYTH-USD", "ig_epic": "", "market_type": "crypto", "binance": "PYTHUSDT"},
    {"name": "Jito", "yahoo": "JTO-USD", "ig_epic": "", "market_type": "crypto", "binance": "JTOUSDT"},
    {"name": "Raydium", "yahoo": "RAY-USD", "ig_epic": "", "market_type": "crypto", "binance": "RAYUSDT"},
    {"name": "Brett", "yahoo": "BRETT11841-USD", "ig_epic": "", "market_type": "crypto", "binance": "BRETTUSDT"},
    {"name": "Book of Meme", "yahoo": "BOME-USD", "ig_epic": "", "market_type": "crypto", "binance": "BOMEUSDT"},
    {"name": "Toncoin", "yahoo": "TON11419-USD", "ig_epic": "", "market_type": "crypto", "binance": "TONUSDT"},
    {"name": "Dogwifhat", "yahoo": "WIF-USD", "ig_epic": "", "market_type": "crypto", "binance": "WIFUSDT"},
    {"name": "Core", "yahoo": "CORE-USD", "ig_epic": "", "market_type": "crypto", "binance": "COREUSDT"},
    {"name": "Mantra", "yahoo": "OM-USD", "ig_epic": "", "market_type": "crypto", "binance": "OMUSDT"},
    {"name": "Kaspa", "yahoo": "KAS-USD", "ig_epic": "", "market_type": "crypto", "binance": "KASUSDT"},
    {"name": "Render Token", "yahoo": "RENDER-USD", "ig_epic": "", "market_type": "crypto", "binance": "RENDERUSDT"},
    {"name": "Worldcoin", "yahoo": "WLD-USD", "ig_epic": "", "market_type": "crypto", "binance": "WLDUSDT"},
    {"name": "Fetcher.ai", "yahoo": "FET-USD", "ig_epic": "", "market_type": "crypto", "binance": "FETUSDT"},
    {"name": "SingularityNET", "yahoo": "AGIX-USD", "ig_epic": "", "market_type": "crypto", "binance": "AGIXUSDT"},
    {"name": "Ocean Protocol", "yahoo": "OCEAN-USD", "ig_epic": "", "market_type": "crypto", "binance": "OCEANUSDT"},
    {"name": "Arkham", "yahoo": "ARKM-USD", "ig_epic": "", "market_type": "crypto", "binance": "ARKMUSDT"},
    {"name": "Pixels", "yahoo": "PIXEL-USD", "ig_epic": "", "market_type": "crypto", "binance": "PIXELUSDT"},
    {"name": "Starknet", "yahoo": "STRK-USD", "ig_epic": "", "market_type": "crypto", "binance": "STRKUSDT"},
    {"name": "Manta", "yahoo": "MANTA-USD", "ig_epic": "", "market_type": "crypto", "binance": "MANTAUSDT"},
    {"name": "Altlayer", "yahoo": "ALT-USD", "ig_epic": "", "market_type": "crypto", "binance": "ALTUSDT"},
    {"name": "Astar", "yahoo": "ASTR-USD", "ig_epic": "", "market_type": "crypto", "binance": "ASTRUSDT"},

    # ── SHARES (94) ──
    # US Tech
    {"name": "Apple", "yahoo": "AAPL", "ig_epic": "UA.D.AAPL.CASH.IP", "market_type": "share"},
    {"name": "Microsoft", "yahoo": "MSFT", "ig_epic": "UA.D.MSFT.CASH.IP", "market_type": "share"},
    {"name": "Amazon", "yahoo": "AMZN", "ig_epic": "UA.D.AMZN.CASH.IP", "market_type": "share"},
    {"name": "Alphabet", "yahoo": "GOOGL", "ig_epic": "UA.D.GOOGL.CASH.IP", "market_type": "share"},
    {"name": "Meta", "yahoo": "META", "ig_epic": "UA.D.FB.CASH.IP", "market_type": "share"},
    {"name": "Tesla", "yahoo": "TSLA", "ig_epic": "UA.D.TSLA.CASH.IP", "market_type": "share"},
    {"name": "NVIDIA", "yahoo": "NVDA", "ig_epic": "UA.D.NVDA.CASH.IP", "market_type": "share"},
    {"name": "Netflix", "yahoo": "NFLX", "ig_epic": "UA.D.NFLX.CASH.IP", "market_type": "share"},
    {"name": "AMD", "yahoo": "AMD", "ig_epic": "UA.D.AMD.CASH.IP", "market_type": "share"},
    {"name": "Intel", "yahoo": "INTC", "ig_epic": "UA.D.INTC.CASH.IP", "market_type": "share"},
    {"name": "Salesforce", "yahoo": "CRM", "ig_epic": "UA.D.CRM.CASH.IP", "market_type": "share"},
    {"name": "Adobe", "yahoo": "ADBE", "ig_epic": "UA.D.ADBE.CASH.IP", "market_type": "share"},
    {"name": "Qualcomm", "yahoo": "QCOM", "ig_epic": "UA.D.QCOM.CASH.IP", "market_type": "share"},
    {"name": "Broadcom", "yahoo": "AVGO", "ig_epic": "UA.D.AVGO.CASH.IP", "market_type": "share"},
    {"name": "Palantir", "yahoo": "PLTR", "ig_epic": "UA.D.PLTR.CASH.IP", "market_type": "share"},
    {"name": "Snowflake", "yahoo": "SNOW", "ig_epic": "UA.D.SNOW.CASH.IP", "market_type": "share"},
    {"name": "CrowdStrike", "yahoo": "CRWD", "ig_epic": "UA.D.CRWD.CASH.IP", "market_type": "share"},
    {"name": "Datadog", "yahoo": "DDOG", "ig_epic": "UA.D.DDOG.CASH.IP", "market_type": "share"},
    {"name": "Shopify", "yahoo": "SHOP", "ig_epic": "UA.D.SHOP.CASH.IP", "market_type": "share"},
    {"name": "Uber", "yahoo": "UBER", "ig_epic": "UA.D.UBER.CASH.IP", "market_type": "share"},
    # US Financials
    {"name": "JPMorgan", "yahoo": "JPM", "ig_epic": "UA.D.JPM.CASH.IP", "market_type": "share"},
    {"name": "Bank of America", "yahoo": "BAC", "ig_epic": "UA.D.BAC.CASH.IP", "market_type": "share"},
    {"name": "Goldman Sachs", "yahoo": "GS", "ig_epic": "UA.D.GS.CASH.IP", "market_type": "share"},
    {"name": "Morgan Stanley", "yahoo": "MS", "ig_epic": "UA.D.MS.CASH.IP", "market_type": "share"},
    # US Other
    {"name": "Berkshire Hathaway", "yahoo": "BRK-B", "ig_epic": "UA.D.BRK.CASH.IP", "market_type": "share"},
    {"name": "Johnson & Johnson", "yahoo": "JNJ", "ig_epic": "UA.D.JNJ.CASH.IP", "market_type": "share"},
    {"name": "Procter & Gamble", "yahoo": "PG", "ig_epic": "UA.D.PG.CASH.IP", "market_type": "share"},
    {"name": "Visa", "yahoo": "V", "ig_epic": "UA.D.V.CASH.IP", "market_type": "share"},
    {"name": "Mastercard", "yahoo": "MA", "ig_epic": "UA.D.MA.CASH.IP", "market_type": "share"},
    {"name": "Coca-Cola", "yahoo": "KO", "ig_epic": "UA.D.KO.CASH.IP", "market_type": "share"},
    {"name": "PepsiCo", "yahoo": "PEP", "ig_epic": "UA.D.PEP.CASH.IP", "market_type": "share"},
    {"name": "Walmart", "yahoo": "WMT", "ig_epic": "UA.D.WMT.CASH.IP", "market_type": "share"},
    {"name": "Costco", "yahoo": "COST", "ig_epic": "UA.D.COST.CASH.IP", "market_type": "share"},
    {"name": "Home Depot", "yahoo": "HD", "ig_epic": "UA.D.HD.CASH.IP", "market_type": "share"},
    {"name": "McDonald's", "yahoo": "MCD", "ig_epic": "UA.D.MCD.CASH.IP", "market_type": "share"},
    {"name": "Disney", "yahoo": "DIS", "ig_epic": "UA.D.DIS.CASH.IP", "market_type": "share"},
    {"name": "ExxonMobil", "yahoo": "XOM", "ig_epic": "UA.D.XOM.CASH.IP", "market_type": "share"},
    {"name": "Chevron", "yahoo": "CVX", "ig_epic": "UA.D.CVX.CASH.IP", "market_type": "share"},
    {"name": "ConocoPhillips", "yahoo": "COP", "ig_epic": "UA.D.COP.CASH.IP", "market_type": "share"},
    {"name": "Pfizer", "yahoo": "PFE", "ig_epic": "UA.D.PFE.CASH.IP", "market_type": "share"},
    {"name": "Eli Lilly", "yahoo": "LLY", "ig_epic": "UA.D.LLY.CASH.IP", "market_type": "share"},
    {"name": "UnitedHealth", "yahoo": "UNH", "ig_epic": "UA.D.UNH.CASH.IP", "market_type": "share"},
    {"name": "Caterpillar", "yahoo": "CAT", "ig_epic": "UA.D.CAT.CASH.IP", "market_type": "share"},
    {"name": "3M", "yahoo": "MMM", "ig_epic": "UA.D.MMM.CASH.IP", "market_type": "share"},
    {"name": "General Electric", "yahoo": "GE", "ig_epic": "UA.D.GE.CASH.IP", "market_type": "share"},
    {"name": "Ford", "yahoo": "F", "ig_epic": "UA.D.F.CASH.IP", "market_type": "share"},
    {"name": "GM", "yahoo": "GM", "ig_epic": "UA.D.GM.CASH.IP", "market_type": "share"},
    {"name": "Rivian", "yahoo": "RIVN", "ig_epic": "UA.D.RIVN.CASH.IP", "market_type": "share"},
    {"name": "Lucid", "yahoo": "LCID", "ig_epic": "UA.D.LCID.CASH.IP", "market_type": "share"},
    {"name": "Coinbase", "yahoo": "COIN", "ig_epic": "UA.D.COIN.CASH.IP", "market_type": "share"},
    {"name": "Robinhood", "yahoo": "HOOD", "ig_epic": "UA.D.HOOD.CASH.IP", "market_type": "share"},
    {"name": "SoFi", "yahoo": "SOFI", "ig_epic": "UA.D.SOFI.CASH.IP", "market_type": "share"},
    {"name": "GameStop", "yahoo": "GME", "ig_epic": "UA.D.GME.CASH.IP", "market_type": "share"},
    {"name": "AMC", "yahoo": "AMC", "ig_epic": "UA.D.AMC.CASH.IP", "market_type": "share"},
    # UK
    {"name": "Shell", "yahoo": "SHEL.L", "ig_epic": "ED.D.SHEL.DAILY.IP", "market_type": "share"},
    {"name": "BP", "yahoo": "BP.L", "ig_epic": "ED.D.BP.DAILY.IP", "market_type": "share"},
    {"name": "HSBC", "yahoo": "HSBA.L", "ig_epic": "ED.D.HSBA.DAILY.IP", "market_type": "share"},
    {"name": "AstraZeneca", "yahoo": "AZN.L", "ig_epic": "ED.D.AZN.DAILY.IP", "market_type": "share"},
    {"name": "GSK", "yahoo": "GSK.L", "ig_epic": "ED.D.GSK.DAILY.IP", "market_type": "share"},
    {"name": "Unilever", "yahoo": "ULVR.L", "ig_epic": "ED.D.ULVR.DAILY.IP", "market_type": "share"},
    {"name": "Diageo", "yahoo": "DGE.L", "ig_epic": "ED.D.DGE.DAILY.IP", "market_type": "share"},
    {"name": "Rio Tinto", "yahoo": "RIO.L", "ig_epic": "ED.D.RIO.DAILY.IP", "market_type": "share"},
    {"name": "BHP Group", "yahoo": "BHP.L", "ig_epic": "ED.D.BHPB.DAILY.IP", "market_type": "share"},
    {"name": "Glencore", "yahoo": "GLEN.L", "ig_epic": "ED.D.GLEN.DAILY.IP", "market_type": "share"},
    {"name": "Lloyds", "yahoo": "LLOY.L", "ig_epic": "ED.D.LLOY.DAILY.IP", "market_type": "share"},
    {"name": "Barclays", "yahoo": "BARC.L", "ig_epic": "ED.D.BARC.DAILY.IP", "market_type": "share"},
    {"name": "NatWest", "yahoo": "NWG.L", "ig_epic": "ED.D.NWG.DAILY.IP", "market_type": "share"},
    {"name": "Vodafone", "yahoo": "VOD.L", "ig_epic": "ED.D.VOD.DAILY.IP", "market_type": "share"},
    {"name": "BT Group", "yahoo": "BT-A.L", "ig_epic": "ED.D.BTA.DAILY.IP", "market_type": "share"},
    {"name": "Tesco", "yahoo": "TSCO.L", "ig_epic": "ED.D.TSCO.DAILY.IP", "market_type": "share"},
    {"name": "Sainsbury's", "yahoo": "SBRY.L", "ig_epic": "ED.D.SBRY.DAILY.IP", "market_type": "share"},
    {"name": "Rolls-Royce", "yahoo": "RR.L", "ig_epic": "ED.D.RR.DAILY.IP", "market_type": "share"},
    {"name": "BAE Systems", "yahoo": "BA.L", "ig_epic": "ED.D.BA.DAILY.IP", "market_type": "share"},
    {"name": "RELX", "yahoo": "REL.L", "ig_epic": "ED.D.REL.DAILY.IP", "market_type": "share"},
    {"name": "London Stock Exchange", "yahoo": "LSEG.L", "ig_epic": "ED.D.LSEG.DAILY.IP", "market_type": "share"},
    {"name": "Flutter", "yahoo": "FLTR.L", "ig_epic": "ED.D.FLTR.DAILY.IP", "market_type": "share"},
    {"name": "Prudential", "yahoo": "PRU.L", "ig_epic": "ED.D.PRU.DAILY.IP", "market_type": "share"},
    {"name": "Standard Chartered", "yahoo": "STAN.L", "ig_epic": "ED.D.STAN.DAILY.IP", "market_type": "share"},
    {"name": "Aviva", "yahoo": "AV.L", "ig_epic": "ED.D.AV.DAILY.IP", "market_type": "share"},
    # EU
    {"name": "SAP", "yahoo": "SAP.DE", "ig_epic": "ED.D.SAP.DAILY.IP", "market_type": "share"},
    {"name": "ASML", "yahoo": "ASML.AS", "ig_epic": "ED.D.ASML.DAILY.IP", "market_type": "share"},
    {"name": "Siemens", "yahoo": "SIE.DE", "ig_epic": "ED.D.SIE.DAILY.IP", "market_type": "share"},
    {"name": "LVMH", "yahoo": "MC.PA", "ig_epic": "ED.D.MC.DAILY.IP", "market_type": "share"},
    {"name": "TotalEnergies", "yahoo": "TTE.PA", "ig_epic": "ED.D.TTE.DAILY.IP", "market_type": "share"},
    {"name": "Airbus", "yahoo": "AIR.PA", "ig_epic": "ED.D.AIR.DAILY.IP", "market_type": "share"},
    {"name": "Nestle", "yahoo": "NESN.SW", "ig_epic": "ED.D.NESN.DAILY.IP", "market_type": "share"},
    {"name": "Novartis", "yahoo": "NOVN.SW", "ig_epic": "ED.D.NOVN.DAILY.IP", "market_type": "share"},
    {"name": "Allianz", "yahoo": "ALV.DE", "ig_epic": "ED.D.ALV.DAILY.IP", "market_type": "share"},

    # ── BONDS (3) ──
    {"name": "US 10Y Treasury", "yahoo": "^TNX", "ig_epic": "IB.D.TNX.DAILY.IP", "market_type": "bond"},
    {"name": "US 30Y Treasury", "yahoo": "^TYX", "ig_epic": "IB.D.TYX.DAILY.IP", "market_type": "bond"},
    {"name": "US 2Y Treasury", "yahoo": "^IRX", "ig_epic": "IB.D.IRX.DAILY.IP", "market_type": "bond"},
]

MARKET_THRESHOLDS = {
    "forex": {
        "rsi_overbought": 70, "rsi_oversold": 30,
        "stoch_overbought": 80, "stoch_oversold": 20,
        "adx_strong": 25, "adx_weak": 18,
        "bb_volatile": 0.04, "bb_trending": 0.025, "bb_ranging": 0.015,
        "strong_buy": 4.0, "buy": 1.5, "sell": -1.5, "strong_sell": -4.0,
    },
    "index": {
        "rsi_overbought": 70, "rsi_oversold": 30,
        "stoch_overbought": 80, "stoch_oversold": 20,
        "adx_strong": 25, "adx_weak": 18,
        "bb_volatile": 0.05, "bb_trending": 0.03, "bb_ranging": 0.018,
        "strong_buy": 4.0, "buy": 1.5, "sell": -1.5, "strong_sell": -4.0,
    },
    "commodity": {
        "rsi_overbought": 70, "rsi_oversold": 30,
        "stoch_overbought": 80, "stoch_oversold": 20,
        "adx_strong": 25, "adx_weak": 18,
        "bb_volatile": 0.06, "bb_trending": 0.035, "bb_ranging": 0.02,
        "strong_buy": 4.0, "buy": 1.5, "sell": -1.5, "strong_sell": -4.0,
    },
    "crypto": {
        "rsi_overbought": 80, "rsi_oversold": 20,
        "stoch_overbought": 85, "stoch_oversold": 15,
        "adx_strong": 30, "adx_weak": 20,
        "bb_volatile": 0.12, "bb_trending": 0.06, "bb_ranging": 0.035,
        "strong_buy": 6.0, "buy": 3.0, "sell": -3.0, "strong_sell": -6.0,
    },
    "share": {
        "rsi_overbought": 70, "rsi_oversold": 30,
        "stoch_overbought": 80, "stoch_oversold": 20,
        "adx_strong": 25, "adx_weak": 18,
        "bb_volatile": 0.06, "bb_trending": 0.035, "bb_ranging": 0.02,
        "strong_buy": 4.0, "buy": 1.5, "sell": -1.5, "strong_sell": -4.0,
    },
    "bond": {
        "rsi_overbought": 65, "rsi_oversold": 35,
        "stoch_overbought": 75, "stoch_oversold": 25,
        "adx_strong": 20, "adx_weak": 15,
        "bb_volatile": 0.03, "bb_trending": 0.02, "bb_ranging": 0.01,
        "strong_buy": 4.0, "buy": 1.5, "sell": -1.5, "strong_sell": -4.0,
    },
}

TIMEFRAME_WEIGHTS = {
    "1d": 0.50,
    "4h": 0.30,
    "1h": 0.20,
    "15m": 0.15,
}
